---
# tasks file for wordpress
- name: Configure /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '127.0.0.1 {{WP_DOMAIN}}'

- name: Nginx directories
  file:
    state: directory
    path: "{{WP_PATH}}/{{item}}"
    owner: www-data
    group: www-data
    recurse: yes
  with_items:
    - public
    - logs

- name: Configure nginx
  template:
    src: wordpress.rdf.loc.j2
    dest: "/etc/nginx/sites-available/{{WP_DOMAIN}}"
  notify: nginx-restart

- name: Configure wordpress in nginx
  file:
    src: "/etc/nginx/sites-available/{{WP_DOMAIN}}"
    dest: "/etc/nginx/sites-enabled/{{WP_DOMAIN}}"
    state: link
  notify: nginx-restart

- meta: flush_handlers

- name: Download wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "{{WP_PATH}}/public"
    remote_src: yes
    group: www-data
    owner: www-data
    extra_opts:
      - "--strip-components=1"

- name: Config kopieren
  copy:
    src: "{{WP_PATH}}/public/wp-config-sample.php"
    dest: "{{WP_PATH}}/public/wp-config.php"
    owner: www-data
    group: www-data
    mode: 0660

- name: Config anpassen
  replace:
    dest: "{{WP_PATH}}/public/wp-config.php"
    regexp: "{{item.regexp}}"
    replace: "{{item.replace}}"
  with_items:
    - {"regexp": "database_name_here", "replace": "{{WP_DB_NAME}}"}
    - {"regexp": "username_here", "replace": "{{WP_DB_USERNAME}}"}
    - {"regexp": "password_here", "replace": "{{WP_DB_PASSWORD}}"}
    - {"regexp": "localhost", "replace": "{{DB_IP}}"}

- name: Config anpassen
  lineinfile:
    dest: "{{WP_PATH}}/public/wp-config.php"
    line: "{{item}}"
  with_items:
  - "define('FS_METHOD', 'direct');"

- name: Rechte auf wordpress
  file:
    path: "{{WP_PATH}}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Setup wp-user and wp-password
  command: curl --silent "http://{{WP_DOMAIN}}/wp-admin/install.php?step=2" --data-urlencode "weblog_title={{WP_DOMAIN}}" --data-urlencode "user_name={{WP_ADMIN_USERNAME}}" --data-urlencode "admin_email={{WP_ADMIN_EMAIL}}" --data-urlencode "admin_password={{WP_ADMIN_PASSWORD}}" --data-urlencode "admin_password2={{WP_ADMIN_PASSWORD}}" --data-urlencode "pw_weak=1" --data-urlencode "blog_public=0"
